properties:
    fields: [no_kel, date, 'no','no_ktp', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat,  status_perkawinan, nama_2, jk_2, tempat_lahir_2, tanggal_lahir_2, no_rek, agama_2, pekerjaan_2, alamat_2, status_perkawinan_2, data_a, data_b]
    tablePk: sk_bn_rekeningid
    tableName: t_sk_bn_rekening
    autosetPostKeys: { add: [no_kel, date, 'no','no_ktp', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat,  status_perkawinan, nama_2, jk_2, tempat_lahir_2, tanggal_lahir_2, no_rek, agama_2, pekerjaan_2, alamat_2, status_perkawinan_2, data_a, data_b], edit: [no_kel, date, 'no','no_ktp', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat,  status_perkawinan, nama_2, jk_2, tempat_lahir_2, tanggal_lahir_2, no_rek, agama_2, pekerjaan_2, alamat_2, status_perkawinan_2, data_a, data_b] }
    dateFields: [date, tanggal_lahir, tanggal_lahir_2]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'SK Beda Nama Rekening'
    func: sk_bn_rekening
    modelName: m_sk_bn_rekening
    menuId: 100
    subject: 'SK Beda Nama Rekening'
    mechIds: [289, 290, 291, 292]
    breadcrumbs: { index: Beranda }
