properties:
    fields: ['no',no_kel, date, nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, nomor_registrasi, tanggal_registrasi, bidang_usaha, lokasi, lingkungan, batas_utara, batas_timur, batas_selatan, batas_barat, berlaku_sampai,nama_usaha,alamat_usaha,luas_tempat_usaha,nama_tetangga_utara,nama_tetangga_timur,nama_tetangga_selatan,nama_tetangga_barat,ttd_kl_nama,ttd_kl_jabatan,ttd_kl_nip]
    tablePk: sk_izin_usahaid
    tableName: t_sk_izin_usaha
    autosetPostKeys: { add: ['no',no_kel, date, nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, nomor_registrasi, tanggal_registrasi, bidang_usaha, lokasi, lingkungan, batas_utara, batas_timur, batas_selatan, batas_barat, berlaku_sampai,nik,nama_usaha,alamat_usaha,luas_tempat_usaha,nama_tetangga_utara,nama_tetangga_timur,nama_tetangga_selatan,nama_tetangga_barat,ttd_kl_nama,ttd_kl_jabatan,ttd_kl_nip], edit: ['no',no_kel, date, nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, nomor_registrasi, tanggal_registrasi, bidang_usaha, lokasi, lingkungan, batas_utara, batas_timur, batas_selatan, batas_barat, berlaku_sampai,nik,nama_usaha,alamat_usaha,luas_tempat_usaha,nama_tetangga_utara,nama_tetangga_timur,nama_tetangga_selatan,nama_tetangga_barat,ttd_kl_nama,ttd_kl_jabatan,ttd_kl_nip] }
    dateFields: [date, tanggal_lahir, tanggal_registrasi, berlaku_sampai]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'Izin Usaha'
    func: sk_izin_usaha
    modelName: m_sk_izin_usaha
    menuId: 77
    subject: 'SK Izin Usaha'
    mechIds: [207, 208, 209, 210]
    breadcrumbs: { index: Beranda }
