properties:
    tablePk: sk_izin_keramaianid
    tableName: t_izin_keramaian
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: jk, 6: tempat_lahir, 7: tanggal_lahir, 8: kewarganegaraan, 9: agama, 10: pekerjaan, 11: alamat, 12: acara, 13: tgl_acara, 14: jam_acara_mulai, 15: jam_acara_selesai, 16: alamat_acara, 17: ttd_nama, 18: ttd_nip, 19: ttd_jabatan, 25: create_on, 26: create_by }, edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, pekerjaan, alamat, acara, tgl_acara, jam_acara_mulai, jam_acara_selesai, alamat_acara, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir, tgl_acara]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK Izin Keramaian'
    func: sk_izin_keramaian
    modelName: m_sk_izin_keramaian
    menuId: '49'
    subject: 'SK SK Izin Keramaian'
    mechIds: ['118', '119', '120', '121']
    breadcrumbs: { index: Beranda }
