properties:
    tablePk: sk_spptid
    tableName: t_sppt
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: jk, 6: tempat_lahir, 7: tanggal_lahir, 8: alamat, 9: bukti_kepemilikan, 10: no_bukti_kepemilikan, 11: luas_bangunan, 12: letak_tanah, 13: no_sppt_asal, 14: atas_nama, 15: ttd_nama, 16: ttd_nip, 17: ttd_jabatan, 23: create_on, 24: create_by }, edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, alamat, bukti_kepemilikan, no_bukti_kepemilikan, luas_bangunan, letak_tanah, no_sppt_asal, atas_nama, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK SPPT'
    func: sk_sppt
    modelName: m_sk_sppt
    menuId: '51'
    subject: 'SK SK SPPT'
    mechIds: ['126', '127', '128', '129']
    breadcrumbs: { index: Beranda }
