properties:
    tablePk: ralat_ktpid
    tableName: t_ralat_ktp
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: jk, 6: tempat_lahir, 7: tanggal_lahir, 8: kewarganegaraan, 9: agama, 10: pekerjaan, 11: alamat, 12: nik_1, 13: nik_2, 14: nik_3, 15: nik_4, 16: ttd_nama, 17: ttd_nip, 18: ttd_jabatan, 24: create_on, 25: create_by }, edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, pekerjaan, alamat, nik_1, nik_2, nik_3, nik_4, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Ralat KTP'
    func: ralat_ktp
    modelName: m_ralat_ktp
    menuId: '24'
    subject: 'SK Ralat KTP'
    mechIds: ['18', '19', '20', '21']
    breadcrumbs: { index: Beranda }
