properties:
    tablePk: sk_izin_lingkunganid
    tableName: sk_izin_lingkungan
    autosetPostKeys: 
        add: [nama_acara,btd_1,btd_2,btd_3,btd_4,btd_5,btd_1_jabatan,btd_2_jabatan,btd_3_jabatan,btd_4_jabatan,btd_5_jabatan,jam_acara,tgl_acara,alamat,syarat,no_kel, date, hari_acara_ext,   nama,  jk,  tempat_lahir,  tanggal_lahir,    pekerjaan,    alamat_acara,jenis_kegiatan,nama_kegiatan,  ttd_nama,  ttd_nip,  ttd_jabatan,  create_on,  create_by]
        edit: [nama_acara,btd_1,btd_2,btd_3,btd_4,btd_5,btd_1_jabatan,btd_2_jabatan,btd_3_jabatan,btd_4_jabatan,btd_5_jabatan,jam_acara,tgl_acara,alamat,syarat, no_kel, date,hari_acara_ext, nama, jk, tempat_lahir, tanggal_lahir,    pekerjaan,  alamat_acara,jenis_kegiatan,nama_kegiatan, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] 
    dateFields: [date, tanggal_lahir,tgl_acara]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Surat Keterangan Izin Lingkungan'
    func: sk_izin_lingkungan
    modelName: m_sk_izin_lingkungan
    menuId: '112'
    subject: 'SK Izin Lingkungan'
    mechIds: [336,337,338,339]
    breadcrumbs: { index: Beranda }
