properties:
    fields: [no_kel, date, 'no', ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, domisili, lingkungan, nama_ketua, alamat_ketua, nama_organisasi, alamat_kantor, berlaku_sampai]
    tablePk: sk_domisili_kantorid
    tableName: t_sk_domisili_kantor
    autosetPostKeys: { add: [no_kel, date, 'no', ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, domisili, lingkungan, nama_ketua, alamat_ketua, nama_organisasi, alamat_kantor, berlaku_sampai], edit: [no_kel, date, 'no', ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, domisili, lingkungan, nama_ketua, alamat_ketua, nama_organisasi, alamat_kantor, berlaku_sampai] }
    dateFields: [date, berlaku_sampai]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'Domisili Kantor'
    func: sk_domisili_kantor
    modelName: m_sk_domisili_kantor
    menuId: 73
    subject: 'SK Domisili Kantor'
    mechIds: [191, 192, 193, 194]
    breadcrumbs: { index: Beranda }
