properties:
    fields: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, tgl_hilang, no_kk]
    tablePk: sk_hilang_kkid
    tableName: t_sk_hilang_kk
    autosetPostKeys: { add: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, tgl_hilang, no_kk], edit: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, tgl_hilang, no_kk] }
    dateFields: [date, tanggal_lahir, tgl_hilang]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'Hilang KK'
    func: sk_hilang_kk
    modelName: m_sk_hilang_kk
    menuId: 71
    subject: 'SK Hilang KK'
    mechIds: [183, 184, 185, 186]
    breadcrumbs: { index: Beranda }
