properties:
    fields: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, tanggal_kebakaran, lokasi, status_perkawinan, yang_terbakar_1, yang_terbakar_2, yang_terbakar_3, yang_terbakar_4]
    tablePk: sk_kebakaranid
    tableName: t_sk_kebakaran
    autosetPostKeys: { add: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, tanggal_kebakaran, lokasi, status_perkawinan, yang_terbakar_1, yang_terbakar_2, yang_terbakar_3, yang_terbakar_4], edit: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, tanggal_kebakaran, lokasi, status_perkawinan, yang_terbakar_1, yang_terbakar_2, yang_terbakar_3, yang_terbakar_4] }
    dateFields: [date, tanggal_lahir, tanggal_kebakaran]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: Kebakaran
    func: sk_kebakaran
    modelName: m_sk_kebakaran
    menuId: 88
    subject: 'SK Kebakaran'
    mechIds: [241, 242, 243, 244]
    breadcrumbs: { index: Beranda }
