properties:
    tablePk: id
    tableName: t_lahir_baru
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: jk, 6: tempat_lahir, 7: tanggal_lahir, 8: pukul, 9: ibu_nama, 10: ibu_nik, 11: ibu_umur, 12: ibu_pekerjaan, 13: ibu_alamat, 14: ayah_nama, 15: ayah_nik, 16: ayah_umur, 17: ayah_pekerjaan, 18: ayah_alamat, 19: pelapor_nama, 20: pelapor_nik, 21: pelapor_umur, 22: pelapor_pekerjaan, 23: pelapor_alamat, 24: hubungan_pelapor, 25: ttd_nama, 26: ttd_nip, 27: ttd_jabatan, 33: create_on, 34: create_by }, edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, pukul, ibu_nama, ibu_nik, ibu_umur, ibu_pekerjaan, ibu_alamat, ayah_nama, ayah_nik, ayah_umur, ayah_pekerjaan, ayah_alamat, pelapor_nama, pelapor_nik, pelapor_umur, pelapor_pekerjaan, pelapor_alamat, hubungan_pelapor, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Lahir Baru'
    func: lahir_baru
    modelName: m_lahir_baru
    menuId: '29'
    subject: 'SK Lahir Baru'
    mechIds: ['38', '39', '40', '41']
    breadcrumbs: { index: Beranda }
