properties:
    tablePk: sk_penghasilanid
    tableName: t_sk_penghasilan
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: jk, 6: tempat_lahir, 7: tanggal_lahir, 8: kewarganegaraan, 9: agama, 10: pekerjaan, 11: alamat, 12: surat_bukti, 13: tgl_berlaku_dari, 14: tgl_berlaku_sampai, 15: ttd_nama, 16: ttd_nip, 17: ttd_jabatan, 23: create_on, 24: create_by }, edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, pekerjaan, alamat, surat_bukti, tgl_berlaku_dari, tgl_berlaku_sampai, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir, tgl_berlaku_dari, tgl_berlaku_sampai]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK Penghasilan'
    func: sk_penghasilan
    modelName: m_sk_penghasilan
    menuId: '37'
    subject: 'SK SK Penghasilan'
    mechIds: ['70', '71', '72', '73']
    breadcrumbs: { index: Beranda }
