properties:
    fields: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, tgl_hilang, no_kk_ktp]
    tablePk: sk_hilang_ktpid
    tableName: t_sk_hilang_ktp
    autosetPostKeys: { add: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, tgl_hilang, no_kk_ktp], edit: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, tgl_hilang, no_kk_ktp] }
    dateFields: [date, tanggal_lahir, tgl_hilang]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'Hilang KTP'
    func: sk_hilang_ktp
    modelName: m_sk_hilang_ktp
    menuId: 70
    subject: 'SK Hilang KTP'
    mechIds: [179, 180, 181, 182]
    breadcrumbs: { index: Beranda }
