properties:
    tablePk: proses_ktpid
    tableName: t_proses_ktp
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: jk, 6: tempat_lahir, 7: tanggal_lahir, 8: kewarganegaraan, 9: agama, 10: pekerjaan, 11: alamat, 12: sbg_persyaratan, 13: ttd_nama, 14: ttd_nip, 15: ttd_jabatan, 21: create_on, 22: create_by }, edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, pekerjaan, alamat, sbg_persyaratan, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Proses KTP'
    func: proses_ktp
    modelName: m_proses_ktp
    menuId: '23'
    subject: 'SK Proses KTP'
    mechIds: ['14', '15', '16', '17']
    breadcrumbs: { index: Beranda }
