properties:
    fields: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, status_perkawinan, no_ktp, nama_usaha, bidang_usaha, tahun_berdiri, lokasi, lingkungan, berlaku_sampai]
    tablePk: sk_tempat_usahaid
    tableName: t_sk_tempat_usaha
    autosetPostKeys: { add: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, status_perkawinan, no_ktp, nama_usaha, bidang_usaha, tahun_berdiri, lokasi, lingkungan, berlaku_sampai], edit: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, status_perkawinan, no_ktp, nama_usaha, bidang_usaha, tahun_berdiri, lokasi, lingkungan, berlaku_sampai] }
    dateFields: [date, tanggal_lahir, berlaku_sampai]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'Tempat Usaha'
    func: sk_tempat_usaha
    modelName: m_sk_tempat_usaha
    menuId: 78
    subject: 'SK Tempat Usaha'
    mechIds: [211, 212, 213, 214]
    breadcrumbs: { index: Beranda }
