properties:
    tablePk: surat_izin_keramaianid
    tableName: surat_izin_keramaian
    autosetPostKeys: 
        add: [jam_acara_mulai,tgl_acara,jam_acara_selesai,alamat,syarat,no_kel, date,  'no',  nama,  jk,  tempat_lahir,  tanggal_lahir,  kewarganegaraan,  agama,    pekerjaan,    alamat_acara, acara,hiburan,  ttd_nama,  ttd_nip,  ttd_jabatan,  create_on,  create_by]
        edit: [jam_acara_mulai,tgl_acara,jam_acara_selesai,alamat,syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama,  pekerjaan,  alamat_acara, acara,hiburan, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] 
    dateFields: [date, tanggal_lahir,tgl_acara]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Surat Izin Keramaian'
    func: surat_izin_keramaian
    modelName: m_surat_izin_keramaian
    menuId: '105'
    subject: 'Surat Izin Keramaian'
    mechIds: [308,309,310,311]
    breadcrumbs: { index: Beranda }
