properties:
    fields: [no_ahli_waris,no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, nomor_registrasi, tanggal_registrasi, ttd_kl_nama, ttd_kl_nip, ttd_kl_jabatan, status_perkawinan, nama_almarhum, tanggal_meninggal, no_surat_kematian]
    tablePk: sk_ahli_warisid
    tableName: t_sk_ahli_waris
    autosetPostKeys: { add: [no_ahli_waris,no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, nomor_registrasi, tanggal_registrasi, ttd_kl_nama, ttd_kl_nip, ttd_kl_jabatan, status_perkawinan, nama_almarhum, tanggal_meninggal, no_surat_kematian], edit: [no_ahli_waris,no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, nomor_registrasi, tanggal_registrasi, ttd_kl_nama, ttd_kl_nip, ttd_kl_jabatan, status_perkawinan, nama_almarhum, tanggal_meninggal, no_surat_kematian] }
    dateFields: [date, tanggal_lahir, tanggal_registrasi, tanggal_meninggal]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'Ahli Waris'
    func: sk_ahli_waris
    modelName: m_sk_ahli_waris
    menuId: 85
    subject: 'SK Ahli Waris'
    mechIds: [229, 230, 231, 232]
    breadcrumbs: { index: Beranda }
