properties:
    fields: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, nama_kapal, daerah_operasi, no_ktp]
    tablePk: sk_hak_milik_kapalid
    tableName: t_sk_hak_milik_kapal
    autosetPostKeys: { add: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, nama_kapal, daerah_operasi, no_ktp], edit: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, nama_kapal, daerah_operasi, no_ktp] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'Hak Milik Kapal'
    func: sk_hak_milik_kapal
    modelName: m_sk_hak_milik_kapal
    menuId: 87
    subject: 'SK Hak Milik Kapal'
    mechIds: [237, 238, 239, 240]
    breadcrumbs: { index: Beranda }
