properties:
    tablePk: sk_kematian_suami_istriid
    tableName: t_kematian_suami_istri
    autosetPostKeys: 
        add: [no_kel,date,'no',nama,alias,bin_binti,jk,tempat_lahir,tanggal_lahir,kewarganegaraan,agama,pekerjaan,alamat,meninggal_nama,meninggal_bin_binti,meninggal_alias,meninggal_jk,meninggal_tempat_lahir,meninggal_tanggal_lahir,meninggal_kewarganegaraan,meninggal_agama,meninggal_pekerjaan,meninggal_alamat,tempat_meninggal,tanggal_meninggal,sebab_meninggal,ttd_nama,ttd_nip,ttd_jabatan,create_on,create_by,syarat]
        edit: [no_kel,date,'no',nama,alias,bin_binti,jk,tempat_lahir,tanggal_lahir,kewarganegaraan,agama,pekerjaan,alamat,meninggal_nama,meninggal_bin_binti,meninggal_alias,meninggal_jk,meninggal_tempat_lahir,meninggal_tanggal_lahir,meninggal_kewarganegaraan,meninggal_agama,meninggal_pekerjaan,meninggal_alamat,tempat_meninggal,tanggal_meninggal,sebab_meninggal,ttd_nama,ttd_nip,ttd_jabatan,update_on,update_by,syarat] 
    dateFields: [date,tanggal_lahir,meninggal_tanggal_lahir,tanggal_meninggal]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK Kematian Suami Istri'
    func: sk_kematian_suami_istri
    modelName: m_sk_kematian_suami_istri
    menuId: '34'
    subject: 'SK SK Kematian Suami Istri'
    mechIds: ['58', '59', '60', '61']
    breadcrumbs: { index: Beranda }
