properties:
    tablePk: sk_belum_memiliki_rumahid
    tableName: sk_belum_memiliki_rumah
    autosetPostKeys: { add: [  syarat,  no_kel,  date,  'no',  nama,  jk,  tempat_lahir,  tanggal_lahir,  kewarganegaraan,  agama,  pekerjaan,  alamat,   ttd_nama,  ttd_nip,  ttd_jabatan,  create_on,  create_by,  domisili,  nik], edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by,domisili,nik] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK Belum Memiliki Rumah'
    func: sk_belum_memiliki_rumah
    modelName: m_sk_belum_memiliki_rumah
    menuId: 110
    subject: 'SK Belum Memiliki Rumah'
    mechIds: [328,329,330,331]
    breadcrumbs: { index: Beranda }
