properties:
    tablePk: sk_duda_jandaid
    tableName: t_sk_duda_janda
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: status, 5: nama, 6: tempat_lahir, 7: tanggal_lahir, 8: kewarganegaraan, 9: agama, 10: pekerjaan, 11: alamat, 12: keterangan, 13: dari_nama, 14: dari_tempat_lahir, 15: dari_tanggal_lahir, 16: dari_kewarganegaraan, 17: dari_agama, 18: dari_pekerjaan, 19: dari_alamat, 20: ttd_nama, 21: ttd_nip, 22: ttd_jabatan, 28: create_on, 29: create_by,30: saksi_1, 31: saksi_2, 32: saksi_3, 33: saksi_4, 34: saksi_5 }, edit: [syarat, no_kel, date, 'no', status, nama, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, pekerjaan, alamat, keterangan, dari_nama, dari_tempat_lahir, dari_tanggal_lahir, dari_kewarganegaraan, dari_agama, dari_pekerjaan, dari_alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by,saksi_1,saksi_2,saksi_3,saksi_4,saksi_5] }
    dateFields: [date, tanggal_lahir, dari_tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK Duda/Janda'
    func: sk_duda_janda
    modelName: m_sk_duda_janda
    menuId: '39'
    subject: 'SK SK Duda/Janda'
    mechIds: ['78', '79', '80', '81']
    breadcrumbs: { index: Beranda }
