properties:
    fields: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, update_on, create_by, update_by, syarat, status_perkawinan, no_ktp, domisili, lingkungan, penghasilan]
    tablePk: sk_penghasilan_lainyaid
    tableName: t_sk_penghasilan_lainya
    autosetPostKeys: { add: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, create_on, create_by, syarat, status_perkawinan, no_ktp, domisili, lingkungan, penghasilan], edit: [no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by, syarat, status_perkawinan, no_ktp, domisili, lingkungan, penghasilan] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [create_on, update_on]
    syaratFields: [syarat]
    sessionUserIdFields: [create_by, update_by]
    behaviour: default
    title: 'SK Penghasilan'
    func: sk_penghasilan_lainya
    modelName: m_sk_penghasilan_lainya
    menuId: 90
    subject: 'SK Penghasilan'
    mechIds: [249, 250, 251, 252]
    breadcrumbs: { index: Beranda }
