properties:
    tablePk: domisili_wniid
    tableName: t_domisili_wni
    autosetPostKeys: 
        add: [alamat,golongan_darah,syarat,no_kel, date,  'no',  nama,  jk,  tempat_lahir,  tanggal_lahir,  kewarganegaraan,  agama,  status_perkawinan,  pekerjaan,  alamat_sekarang,  alamat_asal, berlaku_sampai,domisili,lingkungan,  ttd_nama,  ttd_nip,  ttd_jabatan,  create_on,  create_by]
        edit: [alamat,golongan_darah,syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, status_perkawinan, pekerjaan, alamat_sekarang, alamat_asal, berlaku_sampai,domisili,lingkungan, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] 
    dateFields: [date, tanggal_lahir, berlaku_sampai]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Domisili WNI'
    func: domisili_wni
    modelName: m_domisili_wni
    menuId: '27'
    subject: 'SK Domisili WNI'
    mechIds: ['30', '31', '32', '33']
    breadcrumbs: { index: Beranda }
