properties:
    tablePk: sk_imbid
    tableName: t_imb
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: jk, 6: tempat_lahir, 7: tanggal_lahir, 8: kewarganegaraan, 9: agama, 10: pekerjaan, 11: alamat, 12: panjang, 13: lebar, 14: jml_lantai, 15: luas_teras, 16: pondasi, 17: dinding, 18: atap, 19: lantai, 20: ttd_nama, 21: ttd_nip, 22: ttd_jabatan, 28: create_on, 29: create_by }, edit: [syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama, pekerjaan, alamat, panjang, lebar, jml_lantai, luas_teras, pondasi, dinding, atap, lantai, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK IMB'
    func: sk_imb
    modelName: m_sk_imb
    menuId: '48'
    subject: 'SK SK IMB'
    mechIds: ['114', '115', '116', '117']
    breadcrumbs: { index: Beranda }
