properties:
    tablePk: id
    tableName: t_tidak_mampu
    autosetPostKeys: { add: { 0: syarat, 1: no_kel, 2: date, 3: 'no', 4: nama, 5: tempat_lahir, 6: tanggal_lahir, 7: agama, 8: pekerjaan, 9: alamat, 10: anak_nama, 11: anak_tempat_lahir, 12: anak_tanggal_lahir, 13: anak_agama, 14: anak_pekerjaan, 15: anak_alamat, 16: ttd_nama, 17: ttd_nip, 18: ttd_jabatan, 24: create_on, 25: create_by }, edit: [syarat, no_kel, date, 'no', nama, tempat_lahir, tanggal_lahir, agama, pekerjaan, alamat, anak_nama, anak_tempat_lahir, anak_tanggal_lahir, anak_agama, anak_pekerjaan, anak_alamat, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] }
    dateFields: [date, tanggal_lahir, anak_tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'SK Tidak Mampu'
    func: sk_tidak_mampu
    modelName: m_sk_tidak_mampu
    menuId: '45'
    subject: 'SK SK Tidak Mampu'
    mechIds: ['102', '103', '104', '105']
    breadcrumbs: { index: Beranda }
