config:
  gc:
    methods:
      columns: ['no',nama_kk_asal,date,no_kk_asal,download]
      display_as:
        no_kel: 'Kelurahan'
        no: 'Nomor'
        date: 'Tanggal Surat'
        # pindah_antar: 'Pindah Antar'
        # dusun_dukuh_kampung_asal: 'Dusun/Dukuh/Kampung'
        # dusun_dukuh_kampung_pindah: 'Dusun/Dukuh/Kampung'
        # dusun_dukuh_kampung: 'Dusun/Dukuh/Kampung'
        no_kk_asal: 'Nomor Kartu Keluarga'
        nama_kep_kel_tujuan: 'Nama Kpl. Keluarga'
        no_kk_tujuan: 'Nomor Kartu Keluarga'
        nama_kk_asal: 'Nama Kpl. Keluarga'
        nik_kep_kel_tujuan: 'NIK Kpl. Keluarga'
        alamat_asal: 'Alamat'
        rt_asal: 'RT'
        rw_asal: 'RW'
        kel_asal: 'Desa/Kelurahan'
        kec_asal: 'Kecamatan'
        kab_asal: 'Kabupaten/Kota'
        prop_asal: 'Provinsi'
        kodepos_asal: 'Kode Pos'
        tlp_asal: 'Telp.'
        nik_pemohon: 'NIK Pemohon'
        nama_pemohon: 'Nama Pemohon'
        alasan_pindah_no: 'Alasan Pindah'
        alasan_pindah_lain: 'Tulis Alasan Pindah'
        alamat_pindah: 'Alamat'
        alamat_tujuan: 'Alamat'
        rt_pindah: 'RT'
        rt_tujuan: 'RT'
        rw_tujuan: 'RW'
        rw_pindah: 'RW'
        kel_pindah: 'Desa/Kelurahan'
        kec_pindah: 'Kecamatan'
        kab_pindah: 'Kabupaten/Kota'
        prop_pindah: 'Provinsi'
        kodepos_pindah: 'Kode Pos'
        tlp_pindah: 'Telp.'
        kel_tujuan: 'Desa/Kelurahan'
        kec_tujuan: 'Kecamatan'
        kab_tujuan: 'Kabupaten/Kota'
        prop_tujuan: 'Provinsi'
        kodepos_tujuan: 'Kode Pos'
        tlp_tujuan: 'Telp.'
        klasifikasi_pindah_no: 'Klasifikasi Pindah'
        jenis_kepindahan_no: 'Jenis Kepindahan'
        status_no_kk_tdk_pindah_no: 'Status KK bagi yang tidak Pindah'
        status_no_kk_pindah_no_tujuan: 'Status KK bagi yang Pindah'
        status_no_kk_pindah_no: 'Status No. KK bagi yang Pindah'
        ttd_nama: 'Nama'
        ttd_nip: 'NIP'
        ttd_jabatan: 'Jabatan'
        nama_lurah_tujuan: 'Nama Lurah'
        tgl_diket_lurah_tujuan: 'Tgl. Diketahui'
        nama_camat_tujuan: 'Nama Camat'
        tgl_diket_camat_tujuan: 'Tgl. Diketahui'
        tgl_diket_camat_pindah: 'Tgl. Diketahui'
        tgl_diket_lurah_tujuan: 'Tgl. Diketahui'
        no_diket_lurah_tujuan: 'No. Diket.'
        no_diket_camat_tujuan: 'No. Diket.'
        no_diket_camat_pindah: 'No. Diket.'
        rencana_tgl_pindah: 'Renc. Tgl. Pindah'
        tgl_kedatangan_tujuan: 'Tgl. Kedatangan'
        nip_camat_tujuan: 'NIP'
        nip_lurah_tujuan: 'NIP'
      unset_texteditor: [alamat_asal,alamat_pindah,alamat_tujuan]
      field_type:
        ac_data: [hidden]
        # pindah_antar: [hidden,'Antar Kabupaten / Kota atau Antar Provinsi']
        create_on: [hidden]
        update_on: [hidden]
        create_by: [hidden]
        update_by: [hidden]
        daftar_keluarga_data_pindah: [hidden]
        daftar_keluarga_data_datang: [hidden]
        alasan_pindah_no: [dropdown,data_alasan_pindah_no]
        jenis_kepindahan_no: [dropdown,data_jenis_kepindahan_no]
        klasifikasi_pindah_no: [dropdown,data_klasifikasi_pindah_no]
        status_no_kk_pindah_no_tujuan: [dropdown,data_status_no_kk_pindah_no]
        status_no_kk_pindah_no: [dropdown,data_status_no_kk_pindah_no]
        status_no_kk_tdk_pindah_no: [dropdown,data_status_no_kk_pindah_no]
      fields: [no_prop,no_kab,no_kec,no_kel, no, date, no_kk_asal, nama_kk_asal, prop_asal,kab_asal,kec_asal,kel_asal, alamat_asal, rt_asal, rw_asal, kodepos_asal, tlp_asal, alasan_pindah_no, alasan_pindah_lain, prop_pindah,kab_pindah,kec_pindah,kel_pindah, alamat_pindah, rt_pindah, rw_pindah, kodepos_pindah, tlp_pindah,klasifikasi_pindah_no, jenis_kepindahan_no, status_no_kk_tdk_pindah_no, status_no_kk_pindah_no,rencana_tgl_pindah,no_diket_camat_pindah,tgl_diket_camat_pindah, ttd_nama, ttd_jabatan, ttd_nip, ac_data, daftar_keluarga_data_pindah,daftar_keluarga_data_datang,no_kk_tujuan,nama_kep_kel_tujuan,nik_kep_kel_tujuan,status_no_kk_pindah_no_tujuan,tgl_kedatangan_tujuan,prop_tujuan,kab_tujuan,kec_tujuan,kel_tujuan,alamat_tujuan,rt_tujuan,rw_tujuan,kodepos_tujuan,tlp_tujuan,nama_camat_tujuan,nip_camat_tujuan,no_diket_camat_tujuan,tgl_diket_camat_tujuan,nama_lurah_tujuan,nip_lurah_tujuan,no_diket_lurah_tujuan,tgl_diket_lurah_tujuan, create_on,create_by,update_on,update_by]
      required_fields: [no_kel, 'no', date, no_kk_asal, nama_kk_asal, alamat_asal, rt_asal, rw_asal, kel_asal, kec_asal, kab_asal, prop_asal, kodepos_asal, nik_pemohon, nama_pemohon, alasan_pindah_no, alamat_pindah, rt_pindah, rw_pindah, kel_pindah, kec_pindah, kab_pindah, prop_pindah, kodepos_pindah, klasifikasi_pindah_no,jenis_kepindahan_no, status_no_kk_tdk_pindah_no, status_no_kk_pindah_no,no_kk_tujuan,nik_kep_kel_tujuan,nama_kep_kel_tujuan,tgl_kedatangan_tujuan,prop_tujuan,kab_tujuan,kec_tujuan,kel_tujuan,alamat_tujuan,rt_tujuan,rw_tujuan,kodepos_tujuan, ttd_nama, ttd_jabatan, ttd_nip,status_no_kk_pindah_no_tujuan]
      set_rules:
        kodepos_asal: ['Kode Pos Asal','required|numeric|min_length[5]']
        kodepos_pindah: ['Kode Pos Pindah','required|numeric|min_length[5]']
        kodepos_tujuan: ['Kode Pos Tujuan','required|numeric|min_length[5]']
        tlp_asal: ['Telepon Asal','numeric']
        tlp_pindah: ['Telepon Pindah','numeric']
        no_kk_asal: ['Nomor KK Asal','required|numeric|min_length[10]']
        tlp_tujuan: ['Telepon Tujuan','numeric']
        no_kk_asal: ['Nomor KK Asal','required|numeric|min_length[10]']
        no_kep_kel_tujuan: ['Nomor KK Tujuan','required|numeric|min_length[10]']
        nik_kep_kel_tujuan: ['NIK Kep. Keluarga Tujuan','required|numeric|min_length[16]']
        rt_asal: ['RT Asal','required|numeric|min_length[3]']
        rw_tujuan: ['RW Tujuan','required|numeric|min_length[3]']
        rt_pindah: ['RT Pindah','required|numeric|min_length[3]']
        rw_tujuan: ['RW Tujuan','required|numeric|min_length[3]']