properties:
    tablePk: domisili_pendudukid
    tableName: t_domisili_penduduk
    autosetPostKeys: 
        add: [alamat_asal,nik,keperluan,syarat,no_kel, date,  'no',  nama,  jk,  tempat_lahir,  tanggal_lahir,  kewarganegaraan,  agama,   pekerjaan,    alamat_asal, berlaku_sampai,domisili,  ttd_nama,  ttd_nip,  ttd_jabatan,  create_on,  create_by]
        edit: [alamat_asal,nik,keperluan,syarat, no_kel, date, 'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama,  pekerjaan,  alamat_asal, berlaku_sampai,domisili, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by] 
    dateFields: [date, tanggal_lahir, berlaku_sampai]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Domisili Penduduk'
    func: domisili_penduduk
    modelName: m_domisili_penduduk
    menuId: '103'
    subject: 'SK Domisili Penduduk'
    mechIds: ['299', '300', '301', '302']
    breadcrumbs: { index: Beranda }
