-
    status_pegawai: PTT
    nip: '196303271993011001'
    nip_baru: null
    gelar_nonakademis: ''
    nama_pegawai: 'ASEP DAMIRI,SH'
    jabatan: SEKKEL
    pangkat: ''
    golongan: ''
    unit_kerja: SEKRETARIAT
    gelar_depan: ''
    gelar_belakang: SH
    gender: l
    tempat_lahir: ''
    tanggal_lahir: ''
    agama: ''
    gol_darah: ''
    rhesus: '0'
    status_perkawinan: ''
    nomor_hp: ''
    nomor_tlp_rumah: ''
    foto: e32b1-477683.jpg
    status: '0'
    update_on: '2018-12-01 14:48:21'
    create_on: null
    update_by: '1'
    create_by: null
    archive: '1'
-
    status_pegawai: PTT
    nip: '196511192005011002'
    nip_baru: null
    gelar_nonakademis: ''
    nama_pegawai: 'ATEK ROHMANU,SE'
    jabatan: 'KASI PEMBERDAYAAN MASYARAKAT'
    pangkat: ''
    golongan: ''
    unit_kerja: SEKRETARIAT
    gelar_depan: ''
    gelar_belakang: SE
    gender: l
    tempat_lahir: ''
    tanggal_lahir: ''
    agama: ''
    gol_darah: ''
    rhesus: '0'
    status_perkawinan: ''
    nomor_hp: ''
    nomor_tlp_rumah: ''
    foto: e32b1-477683.jpg
    status: '0'
    update_on: '2018-12-01 14:48:21'
    create_on: null
    update_by: '1'
    create_by: null
    archive: '1'
-
    status_pegawai: PTT
    nip: '196404221984121002'
    nip_baru: null
    gelar_nonakademis: ''
    nama_pegawai: 'DADANG HERIYANTO,BSc.SH'
    jabatan: 'KASI TRANTIBUM'
    pangkat: ''
    golongan: ''
    unit_kerja: SEKRETARIAT
    gelar_depan: ''
    gelar_belakang: 'BSc.SH'
    gender: l
    tempat_lahir: ''
    tanggal_lahir: ''
    agama: ''
    gol_darah: ''
    rhesus: '0'
    status_perkawinan: ''
    nomor_hp: ''
    nomor_tlp_rumah: ''
    foto: e32b1-477683.jpg
    status: '0'
    update_on: '2018-12-01 14:48:21'
    create_on: null
    update_by: '1'
    create_by: null
    archive: '1'
-
    status_pegawai: PTT
    nip: '196307252007011013'
    nip_baru: null
    gelar_nonakademis: ''
    nama_pegawai: 'T A U H I D'
    jabatan: 'PELAKSANA'
    pangkat: ''
    golongan: ''
    unit_kerja: SEKRETARIAT
    gelar_depan: ''
    gelar_belakang: ''
    gender: l
    tempat_lahir: ''
    tanggal_lahir: ''
    agama: ''
    gol_darah: ''
    rhesus: '0'
    status_perkawinan: ''
    nomor_hp: ''
    nomor_tlp_rumah: ''
    foto: e32b1-477683.jpg
    status: '0'
    update_on: '2018-12-01 14:48:21'
    create_on: null
    update_by: '1'
    create_by: null
    archive: '1'