properties:
    tablePk: sk_kelakuan_baikid
    tableName: sk_kelakuan_baik
    autosetPostKeys: 
        add: [keperluan,syarat,  no_kel,  date,alamat, 'no',  nama,  jk,  tempat_lahir,  tanggal_lahir,  kewarganegaraan,  agama,    pekerjaan,    nik,    ttd_nama,  ttd_nip,  ttd_jabatan,  create_on,  create_by ]
        edit: [keperluan,syarat, no_kel, date,alamat,'no', nama, jk, tempat_lahir, tanggal_lahir, kewarganegaraan, agama,  pekerjaan,  nik, ttd_nama, ttd_nip, ttd_jabatan, update_on, update_by]
    dateFields: [date, tanggal_lahir]
    currentDateFields: [update_on, create_on]
    syaratFields: [syarat]
    sessionUserIdFields: [update_by, create_by]
    behaviour: default
    title: 'Surat Keterangan Kelakuan Baik'
    func: sk_kelakuan_baik
    modelName: m_sk_kelakuan_baik
    menuId: '107'
    subject: 'SK Kelakuan Baik'
    mechIds: [316,317,318,319]
    breadcrumbs: { index: Beranda }
